#spring.application.name=springboot-developer
spring:
  application:
    name: springboot-developer #will remove??
  jpa:
    #?? ?? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    #??? ?? ?? data.sql ??
    defer-datasource-initialization: true